### PR TITLE
Differentiate environments kartlag

### PR DESCRIPTION
**Pull request by kepatinin**
Kartlag uses the environment based on host, and shows sublayers depending on the fields "publisertest" and "publiserprod"

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_394

**Review by bjornreppen — APPROVED** [review]
Good job!  Sometimes if 3000 is busy for local you get asked whether you want to run on 3001 for example.. coiuld have used window.location.hostname to get rid of port... but details.

**Comment by kepatinin** [comment]
Good tip! I'll use hostname for localhost 👍

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_394

**Pull request merged**
