### PR TITLE
No crossing polygons

### PR DESCRIPTION
**Pull request by kepatinin**
Main changes:
- Infobox opens when clicking on the map buttons
- Do not allow drawing polygons with lines intersecting

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_329

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_329

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_329

**Review by bjornreppen — APPROVED** [review]
Gold plated! Excellent!

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_329

**Pull request merged**
