### PR TITLE
Better automatic zoom

### PR DESCRIPTION
**Pull request by kepatinin**
Automatic zoom when selecting search results. The zoom is calculated based on fylke, kommune or eiendom geometry, depending on what has been selected.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_365

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_365

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_365

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_365

**Review by bjornreppen — APPROVED** [review]
Great job!

**Pull request merged**
