### PR TITLE
Add field infobox result

### PR DESCRIPTION
**Pull request by kepatinin**
Infobox details show not only the result from GetFeatureInfo, but also the property name (key). This key uses a "translation" model to show the correct term in the UI.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_346

**Review by bjornreppen — APPROVED** [review]
Good job!

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_346

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_346

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_346

**Pull request merged**
