### PR TITLE
Faktaark per sublag

### PR DESCRIPTION
**Pull request by kepatinin**
- Faktaark ulr can be defined at layer and sublayer level. In addition, variables contained in curly brackets {} can be used in the url (similar to klikktekst).
- Faktaark link is nor shown in a list item instead of just an icon as before.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_363

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_363

**Review by bjornreppen — APPROVED** [review]
Great job!

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_363

**Pull request merged**
