### PR TITLE
Polygon panel

### PR DESCRIPTION
**Pull request by kepatinin**
Polygons are created and edited from an infobox instead of from kartlag panel.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_328

**Review by bjornreppen — APPROVED** [review]
Very nice!

How do you get the polygon panel back after closing it?

**Comment by kepatinin** [comment]
You can click on the polygon and the infobox will open again.

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_328

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_328

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_328

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_328

**Pull request merged**
