### PR TITLE
Small infobox for mobile

### PR DESCRIPTION
**Pull request by kepatinin**
When clicking ont he map in mobile, a small infobox opens first. Clicking in teh marker or in the small infobox will open the full screen infobox. 
Desktop keeps same functionality as before.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_318

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_318

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_318

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_318

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_318

**Comment by kepatinin** [comment]
Not preferred version.

**Pull request closed without merging**
