### PR TITLE
Search results format

### PR DESCRIPTION
**Pull request by kepatinin**
Change format of search results so list items are larger and style is similar to the rest of the application.

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_325

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_325

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_325

**Review by bjornreppen — APPROVED** [review]
High quality as usual

**Pull request merged**
