### PR TITLE
Test back button on mobile for infobox and legend

### PR DESCRIPTION
**Pull request by kepatinin**
Trying to make the back button work on mobile

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_313

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_313

**Comment by artsdatabank** [comment]
Test den: https://forvaltningsportal.test.artsdatabanken.no/pr/forvaltningsportal_313

**Comment by kepatinin** [comment]
Needs to be done again, not working properly.

**Pull request closed without merging**
